[package]
name = "rustTest"
version = "0.1.0"
authors = ["filipot <filipot@stud.ntnu.no>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[[bin]]
name = "rustTest"
path = "src/main.rs"
